# Generated by Django 2.2.16 on 2021-10-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211017_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Дата', 'verbose_name_plural': ('Даты',)},
        ),
    ]
